MagicWordCounterOnline/Controllers/CountingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MagicWordCounter.Core;

namespace MagicWordCounterOnline.Controllers
{
    public class CountingController : Controller
    {
        // GET: Counting
        public ActionResult Index()
        {
            var viewModel = new WordCountingViewModel();
            return View(viewModel);
        }

        // POST: Counting
        [HttpPost]
        public ActionResult Index(WordCountingViewModel viewModel)
        {
            viewModel.UpdateWordCount.Execute(null);
            return View(viewModel);
        }
    }
}

MagicWordCounterOnline/Views/Counting/Index.cshtml
@model MagicWordCounter.Core.WordCountingViewModel
@{
    ViewBag.Title = "Index";
}

<h2>Magic Word Counter</h2>
<i>The Magic Website</i>
<hr />
@using (Html.BeginForm("Index", "Counting", FormMethod.Post, new { @class = "form-horizontal" }))
{
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                Text to count:<br />
                @Html.TextAreaFor(x => x.TextToCount, new { style = "width: 100%; height: 350px;" })
                <br />
                <br />
                <div class="checkbox">
                    <label>
                        @Html.CheckBoxFor(x => x.ExcludeArticles)
                        Exclude articles
                    </label>
                </div>
                <div class="checkbox">
                    <label>
                        @Html.CheckBoxFor(x => x.CountQuotesAsOneWord)
                        Count quotes as one word
                    </label>
                </div>
            </div>
        </div>        
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <input type="submit" value="Count" class="btn btn-default" />
            </div>
        </div>        
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <b>@Html.DisplayFor(x => x.WordCountDisplay)</b>
            </div>
        </div>        
    </div>

}

MagicWordCounterOnline/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Magic Word Counter</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Magic Word Counter", "Index", "Counting", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Count", "Index", "Counting")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - devnet</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>